/**
 * GENERATED by scripts/generate-marks.mjs from the approved design board.
 * Do not hand-edit — regenerate instead.
 *
 * Every symbol here is lifted verbatim from `Board 03 - Home.dc.html`, which
 * itself lifted them from the design system's section 05. Nothing is redrawn.
 *
 * Construction, which the <Mark> component enforces: a 100-unit viewBox, the
 * silhouette filled in its family tint and offset +4/+4 down-right, and the
 * ink-line path stroked over it. Abstract marks (sea, wind, reef, depth, palm,
 * offline, coral fan) carry no silhouette, so their `shape` is empty.
 * `weave` is NOT abstract: it is the Bedouin divider, a filled diamond.
 */

/** A shape token name; resolves to `var(--color-<name>)`. */
export type MarkTint =
  | 'shape-water'
  | 'shape-life'
  | 'shape-land'
  | 'cat-wellness-shape'
  | 'cat-transfers-shape';

export interface MarkGlyph {
  /** Filled silhouette, offset +4/+4 behind the line. Empty for abstract marks. */
  readonly shape: string;
  /** The ink-line path drawn over the silhouette. */
  readonly d: string;
  readonly tint: MarkTint;
}

export const MARKS = {
  sun: { shape: "M32 50a18 18 0 1 0 36 0a18 18 0 1 0 -36 0z", d: "M50 32a18 18 0 1 0 .5 0M50 8v10M50 82v10M8 50h10M82 50h10M20 20l7 7M73 73l7 7M80 20l-7 7M27 73l-7 7", tint: 'shape-land' },
  sea: { shape: "", d: "M10 40c14-14 26-14 40 0 14-14 26-14 40 0M10 64c14-14 26-14 40 0 14-14 26-14 40 0", tint: 'shape-water' },
  fish: { shape: "M14 50a24 19 0 1 0 48 0a24 19 0 1 0 -48 0zM62 40l16 10-16 10z", d: "M14 50a24 19 0 1 0 48 0a24 19 0 1 0 -48 0zM62 40l16 10-16 10zM26 44h.5", tint: 'shape-life' },
  coralFan: { shape: "", d: "M50 86V42M50 56 30 34M50 56 70 34M50 44 34 20M50 44 66 20M50 68 22 52M50 68 78 52", tint: 'shape-life' },
  turtle: { shape: "M24 50a26 26 0 1 0 52 0a26 26 0 1 0 -52 0z", d: "M50 24a26 26 0 1 0 .5 0M50 20V6M22 34 12 24M78 34l10-10M28 72l-8 12M72 72l8 12", tint: 'shape-water' },
  jellyfish: { shape: "M50 18c14 0 23 11 23 26 0 12-8 18-8 28 0 7-7 12-15 12s-15-5-15-12c0-10-8-16-8-28 0-15 9-26 23-26z", d: "M50 18c14 0 23 11 23 26 0 12-8 18-8 28 0 7-7 12-15 12s-15-5-15-12c0-10-8-16-8-28 0-15 9-26 23-26z", tint: 'shape-life' },
  shell: { shape: "M50 86C30 86 16 68 16 48 16 28 31 14 50 14s34 14 34 34c0 20-14 38-34 38z", d: "M50 86C30 86 16 68 16 48 16 28 31 14 50 14s34 14 34 34c0 20-14 38-34 38zM50 14v72M26 24l14 58M74 24 60 82", tint: 'shape-life' },
  bubbles: { shape: "M20 74a12 12 0 1 0 24 0a12 12 0 1 0 -24 0zM52 48a8 8 0 1 0 16 0a8 8 0 1 0 -16 0zM40 24a6 6 0 1 0 12 0a6 6 0 1 0 -12 0z", d: "M32 74a12 12 0 1 0 .5 0M60 48a8 8 0 1 0 .5 0M46 24a6 6 0 1 0 .5 0", tint: 'shape-water' },
  reef: { shape: "", d: "M10 88c8-18 16-18 24 0M34 88c8-26 16-26 24 0M58 88c8-18 16-18 24 0", tint: 'shape-life' },
  diver: { shape: "M41 20a9 9 0 1 0 18 0a9 9 0 1 0 -18 0z", d: "M50 14a9 9 0 1 0 .5 0M50 32v28M50 60 30 88M50 60l20 28M32 42h36", tint: 'shape-water' },
  mask: { shape: "M16 34h68v24a14 14 0 0 1-14 14H30a14 14 0 0 1-14-14z", d: "M16 34h68v24a14 14 0 0 1-14 14H30a14 14 0 0 1-14-14zM50 72v16M16 48h68", tint: 'shape-water' },
  tank: { shape: "M36 32a14 14 0 0 1 28 0v50H36z", d: "M36 32a14 14 0 0 1 28 0v50H36zM50 10v22M36 52h28", tint: 'shape-water' },
  fin: { shape: "M38 14h24l6 48-18 24-18-24z", d: "M38 14h24l6 48-18 24-18-24zM50 26v36", tint: 'shape-water' },
  depth: { shape: "", d: "M50 12v54M32 50l18 18 18-18M14 86h72", tint: 'shape-water' },
  wind: { shape: "", d: "M12 32h48a14 14 0 1 0-14-14M12 54h60a14 14 0 1 1-14 14M12 76h26", tint: 'shape-water' },
  moon: { shape: "M62 12a38 38 0 1 0 20 68A40 40 0 0 1 62 12z", d: "M62 12a38 38 0 1 0 20 68A40 40 0 0 1 62 12z", tint: 'shape-land' },
  palm: { shape: "", d: "M50 88V36M50 36C34 18 20 20 12 30M50 36c16-18 30-16 38-6M50 36c-4-18 0-26 8-30M50 36c4-18 0-26-8-30", tint: 'shape-land' },
  camel: { shape: "M18 62c0-11 5-18 14-20 3-9 8-14 14-14s11 5 13 13c3-7 7-11 12-11 9 0 15 8 15 19v13z", d: "M18 62c0-11 5-18 14-20 3-9 8-14 14-14s11 5 13 13c3-7 7-11 12-11 9 0 15 8 15 19v13H18zM24 62v22M38 62v22M66 62v22M80 62v22M80 43V30a11 11 0 0 1 11-11M91 19l6-5", tint: 'shape-land' },
  dunes: { shape: "M6 68c16-24 32-24 48 0 12-16 24-16 36 0v18H6z", d: "M6 68c16-24 32-24 48 0M44 68c12-16 24-16 36 0M6 86h84", tint: 'shape-land' },
  canyon: { shape: "M12 88V32l16-16 16 28 12-12 12 24 16-8v40z", d: "M12 88V32l16-16 16 28 12-12 12 24 16-8v40z", tint: 'shape-land' },
  tent: { shape: "M50 14 14 84h72z", d: "M50 14 14 84h72zM50 14v70", tint: 'shape-land' },
  kite: { shape: "M50 12 80 42 50 72 20 42z", d: "M50 12 80 42 50 72 20 42zM50 72v18M36 90h28", tint: 'shape-life' },
  sail: { shape: "M50 20 76 68H24zM14 72h72l-9 12H23z", d: "M50 12v56M50 20 76 68H24M14 72h72l-9 12H23z", tint: 'shape-water' },
  tea: { shape: "M22 36h44v22a18 18 0 0 1-18 18h-8a18 18 0 0 1-18-18z", d: "M22 36h44v22a18 18 0 0 1-18 18h-8a18 18 0 0 1-18-18zM66 44h10a9 9 0 0 1 0 18H66M16 86h56", tint: 'shape-land' },
  weave: { shape: "M0 50 16 34 32 50 16 66zM32 50 48 34 64 50 48 66zM64 50 80 34 96 50 80 66z", d: "M0 50 16 34 32 50 16 66zM32 50 48 34 64 50 48 66zM64 50 80 34 96 50 80 66z", tint: 'shape-land' },
  arch: { shape: "M20 88V40a30 30 0 0 1 60 0v48z", d: "M20 88V40a30 30 0 0 1 60 0v48M50 88V64", tint: 'shape-land' },
  compass: { shape: "M12 50a38 38 0 1 0 76 0a38 38 0 1 0 -76 0z", d: "M50 12a38 38 0 1 0 .5 0M34 66l10-24 22-8-10 24z", tint: 'shape-water' },
  camera: { shape: "M14 32h16l6-10h28l6 10h16v46H14z", d: "M14 32h16l6-10h28l6 10h16v46H14zM50 50a14 14 0 1 0 .5 0", tint: 'shape-life' },
  star: { shape: "M50 16 62 42l28 3-21 19 6 27-25-14-25 14 6-27L10 45l28-3z", d: "M50 16 62 42l28 3-21 19 6 27-25-14-25 14 6-27L10 45l28-3z", tint: 'shape-land' },
  chat: { shape: "M14 20h72v44H36L14 84z", d: "M14 20h72v44H36L14 84z", tint: 'shape-water' },
  noFly: { shape: "M50 16l10 26h28l-22 17 8 27-24-16-24 16 8-27L12 42h28z", d: "M50 16l10 26h28l-22 17 8 27-24-16-24 16 8-27L12 42h28zM12 12l76 76", tint: 'shape-life' },
  chamber: { shape: "M14 34h48a16 16 0 0 1 0 32H14z", d: "M14 34h48a16 16 0 0 1 0 32H14zM14 34v32M44 42v16", tint: 'shape-water' },
  firstAid: { shape: "M18 28h64v52H18z", d: "M18 28h64v52H18zM50 40v28M36 54h28M36 28V14h28v14", tint: 'shape-life' },
  sos: { shape: "M50 14 90 84H10z", d: "M50 14 90 84H10zM50 42v18M50 70h.5", tint: 'shape-life' },
  eco: { shape: "M86 14c0 40-22 56-48 56H14c0-40 22-56 48-56z", d: "M86 14c0 40-22 56-48 56H14c0-40 22-56 48-56M14 86c8-26 26-40 48-48", tint: 'cat-wellness-shape' },
  offline: { shape: "", d: "M20 54a32 32 0 0 1 50-14M34 72a18 18 0 0 1 24-7M50 86h.5M14 14l72 72", tint: 'shape-water' },
  pass: { shape: "M16 16h26v26H16zM58 16h26v26H58zM16 58h26v26H16z", d: "M16 16h26v26H16zM58 16h26v26H58zM16 58h26v26H16zM58 58h10v10H58zM74 74h10v10H74z", tint: 'shape-water' },
} as const satisfies Record<string, MarkGlyph>;

export type MarkName = keyof typeof MARKS;

/** The same hand, drawn larger. Empty states and detail headers. */
export const ILLOS = {
  seaTurtle: { shape: "M24 50a26 26 0 1 0 52 0a26 26 0 1 0 -52 0z", d: "M50 24a26 26 0 1 0 .5 0M50 20V6M22 34 12 24M78 34l10-10M28 72l-8 12M72 72l8 12", tint: 'shape-water' },
  jellyfish: { shape: "M50 14c15 0 25 12 25 28 0 13-9 19-9 30 0 8-7 14-16 14s-16-6-16-14c0-11-9-17-9-30 0-16 10-28 25-28z", d: "M50 14c15 0 25 12 25 28 0 13-9 19-9 30 0 8-7 14-16 14s-16-6-16-14c0-11-9-17-9-30 0-16 10-28 25-28z", tint: 'shape-life' },
  lionfish: { shape: "M28 52a23 19 0 1 0 46 0a23 19 0 1 0 -46 0zM74 42l14 10-14 10z", d: "M28 52a23 19 0 1 0 46 0a23 19 0 1 0 -46 0zM74 42l14 10-14 10zM38 46h.5M40 34 34 14M52 30 50 10M64 34 70 14M40 70 34 90M52 74 50 92M64 70 70 90", tint: 'shape-land' },
  coralFan: { shape: "", d: "M50 88V42M50 58 28 34M50 58 72 34M50 44 32 18M50 44 68 18M50 72 20 54M50 72 80 54", tint: 'shape-life' },
  camel: { shape: "M18 60c0-12 5-19 14-21 3-10 8-16 15-16s12 6 14 14c3-8 8-12 13-12 10 0 16 9 16 21v14z", d: "M18 60c0-12 5-19 14-21 3-10 8-16 15-16s12 6 14 14c3-8 8-12 13-12 10 0 16 9 16 21v14H18zM24 60v26M39 60v26M69 60v26M84 60v26M84 40V26a12 12 0 0 1 12-12", tint: 'shape-land' },
  dhow: { shape: "M50 20 74 68H26zM14 72h72l-9 13H23z", d: "M50 12v58M50 20 74 68H26M14 72h72l-9 13H23z", tint: 'shape-water' },
} as const satisfies Record<string, MarkGlyph>;

export type IlloName = keyof typeof ILLOS;

/** The twelve categories, in the order the design system lists them. */
export const CATEGORY_MARKS = {
  diving: { shape: "M38 14h24l6 48-18 24-18-24z", d: "M38 14h24l6 48-18 24-18-24zM50 26v36", tint: 'shape-water' },
  freediving: { shape: "", d: "M50 12v40M50 52c14 0 22 12 22 34M50 52c-14 0-22 12-22 34", tint: 'shape-water' },
  snorkeling: { shape: "M16 38h38a16 16 0 0 1 0 32H34a18 18 0 0 1-18-18z", d: "M16 38h38a16 16 0 0 1 0 32H34M72 38V20h14", tint: 'shape-water' },
  boatSea: { shape: "M50 20 76 68H24zM16 72h68l-9 12H25z", d: "M50 12v56M50 20 76 68H24M16 72h68l-9 12H25z", tint: 'shape-water' },
  courses: { shape: "M16 24h68v44H16z", d: "M16 24h68v44H16zM50 38v20M38 82h24", tint: 'shape-water' },
  kiteWatersports: { shape: "M50 12 80 40 50 68 20 40z", d: "M50 12 80 40 50 68 20 40zM50 68v20M36 88h28", tint: 'shape-life' },
  foodCooking: { shape: "M22 40h44v18a18 18 0 0 1-18 18h-8a18 18 0 0 1-18-18z", d: "M22 40h44v18a18 18 0 0 1-18 18h-8a18 18 0 0 1-18-18zM66 46h10a9 9 0 0 1 0 18H66M16 86h56", tint: 'shape-life' },
  rentals: { shape: "M14 54 54 14h32v32L46 86z", d: "M14 54 54 14h32v32L46 86zM68 32h.5", tint: 'shape-life' },
  desertSafari: { shape: "M10 70c14-24 26-24 40 0 14-24 26-24 40 0v14H10z", d: "M10 70c14-24 26-24 40 0 14-24 26-24 40 0", tint: 'shape-land' },
  bedouinCulture: { shape: "M50 14 14 84h72z", d: "M50 14 14 84h72zM50 14v70", tint: 'shape-land' },
  wellnessYoga: { shape: "M22 84 50 58l28 26z", d: "M50 14a9 9 0 1 0 .5 0M50 32v26M22 84l28-26 28 26M28 50h44", tint: 'cat-wellness-shape' },
  transfers: { shape: "M14 62V46l10-20h52l10 20v16z", d: "M14 62V46l10-20h52l10 20v16zM30 76h.5M70 76h.5", tint: 'cat-transfers-shape' },
} as const satisfies Record<string, MarkGlyph>;

export type CategoryMarkName = keyof typeof CATEGORY_MARKS;
