/**
 * Generates src/marks.ts from the approved design board.
 *
 * The marks live in @dahab/tokens rather than in a UI package because they
 * are design-system DATA, exactly like the colour ramps — and because both
 * the web console and the React Native apps need them. A UI package cannot
 * be the source for a surface built on the other runtime.
 *
 * The 37 marks, the 6 illustrations and the 12 category marks are lifted
 * VERBATIM out of `Board 03 - Home.dc.html`'s script block, so no symbol on any
 * surface is ever a redraw. Run this again if the board's arrays change.
 *
 *   node scripts/generate-marks.mjs <path to Board 03 - Home.dc.html>
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const boardPath = process.argv[2];
if (!boardPath) {
  console.error('usage: node scripts/generate-marks.mjs <Board 03 - Home.dc.html>');
  process.exit(1);
}

const source = readFileSync(boardPath, 'utf8');
const script = source.slice(source.indexOf('text/x-dc'));

// lint:hardcoded allow=hex — these are not design decisions. They are the
// design board's OWN constants, needed to evaluate its arrays and to map each
// tint onto a token name; the generated output contains no hex at all.

/** The board's own constants, so the arrays evaluate exactly as they render. */
const MINT = '#A8E2DC';
const BLUSH = '#F9CFC8';
const SAND = '#F0DDB0';
const CIRC = (cx, cy, r) =>
  `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${r * 2} 0a${r} ${r} 0 1 0 ${-r * 2} 0z`;

function grab(name) {
  const start = script.indexOf(`const ${name} = [`);
  if (start === -1) throw new Error(`${name} not found in the board`);
  const open = script.indexOf('[', start);
  let depth = 0;
  for (let i = open; i < script.length; i += 1) {
    if (script[i] === '[') depth += 1;
    else if (script[i] === ']') {
      depth -= 1;
      if (depth === 0) {
        // eslint-disable-next-line no-eval -- the board is a trusted local artefact
        return eval(script.slice(open, i + 1));
      }
    }
  }
  throw new Error(`${name} is unterminated`);
}

const MARKS = grab('MARKS');
const ILLOS = grab('ILLOS');
const CATS = grab('CATS');

/**
 * Tints become token NAMES, never hexes: that keeps the marks inside the token
 * package's authority and lets Night Dive dim every silhouette for free.
 */
const TINT_TOKEN = {
  [MINT]: 'shape-water',
  [BLUSH]: 'shape-life',
  [SAND]: 'shape-land',
  '#D6DDC9': 'cat-wellness-shape',
  '#E3C8BA': 'cat-transfers-shape',
};

const unmapped = [...MARKS, ...ILLOS, ...CATS].filter((m) => !TINT_TOKEN[m.tint]);
if (unmapped.length > 0) {
  throw new Error(`unmapped tint: ${unmapped.map((m) => `${m.name} ${m.tint}`).join(', ')}`);
}

const camel = (name) => {
  const words = name
    .replace(/&/g, ' ')
    .replace(/[^A-Za-z0-9 -]/g, '')
    .trim()
    .split(/[-\s]+/)
    .filter(Boolean);
  // "SOS" must become `sos`, not `sOS`: lower each word whole before
  // title-casing it, so an all-caps acronym reads as an identifier.
  return words
    .map((word, index) => {
      const lower = word.toLowerCase();
      return index === 0 ? lower : lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('');
};

const entries = (list) =>
  list
    .map(
      (m) =>
        `  ${camel(m.name)}: { shape: ${JSON.stringify(m.shape)}, d: ${JSON.stringify(m.d)}, tint: '${TINT_TOKEN[m.tint]}' },`,
    )
    .join('\n');

const tints = [...new Set(Object.values(TINT_TOKEN))].map((t) => `  | '${t}'`).join('\n');

const out = `/**
 * GENERATED by scripts/generate-marks.mjs from the approved design board.
 * Do not hand-edit — regenerate instead.
 *
 * Every symbol here is lifted verbatim from \`Board 03 - Home.dc.html\`, which
 * itself lifted them from the design system's section 05. Nothing is redrawn.
 *
 * Construction, which the <Mark> component enforces: a 100-unit viewBox, the
 * silhouette filled in its family tint and offset +4/+4 down-right, and the
 * ink-line path stroked over it. Abstract marks (sea, wind, reef, depth, palm,
 * offline, coral fan) carry no silhouette, so their \`shape\` is empty.
 * \`weave\` is NOT abstract: it is the Bedouin divider, a filled diamond.
 */

/** A shape token name; resolves to \`var(--color-<name>)\`. */
export type MarkTint =
${tints};

export interface MarkGlyph {
  /** Filled silhouette, offset +4/+4 behind the line. Empty for abstract marks. */
  readonly shape: string;
  /** The ink-line path drawn over the silhouette. */
  readonly d: string;
  readonly tint: MarkTint;
}

export const MARKS = {
${entries(MARKS)}
} as const satisfies Record<string, MarkGlyph>;

export type MarkName = keyof typeof MARKS;

/** The same hand, drawn larger. Empty states and detail headers. */
export const ILLOS = {
${entries(ILLOS)}
} as const satisfies Record<string, MarkGlyph>;

export type IlloName = keyof typeof ILLOS;

/** The twelve categories, in the order the design system lists them. */
export const CATEGORY_MARKS = {
${entries(CATS)}
} as const satisfies Record<string, MarkGlyph>;

export type CategoryMarkName = keyof typeof CATEGORY_MARKS;
`;

writeFileSync(resolve(here, '../src/marks.ts'), out);
console.log(
  `generate-marks: ${MARKS.length} marks, ${ILLOS.length} illustrations, ${CATS.length} category marks.`,
);
