import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, rename, rm, stat } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { Readable } from 'node:stream';
import { fileURLToPath } from 'node:url';

/**
 * Where uploaded files live.
 *
 * One interface, because the answer changes between development and
 * production and nothing above this file should have to know. On this machine
 * the files sit on the local disk under `apps/api/.media`; in production the
 * same calls go to Supabase Storage in the project that already holds the
 * database. Swapping them is one environment variable and one class, and the
 * `storage_key` written to `media_uploads` means the same thing in both.
 *
 * What a store hands back as a URL is deliberately allowed to differ:
 *
 *   local     a root-relative path, `/media/<key>`, resolved by the client
 *             against the API's own origin — so moving the API to another
 *             port or host does not strand every picture already posted
 *   supabase  an absolute public URL on the storage CDN
 *
 * A client that sees a path starting with `/` prefixes the API base; one that
 * sees `https://` uses it as it is. That is the whole contract.
 */
export interface MediaStore {
  /** Moves a finished temp file into the store under `key`. */
  commit(tempPath: string, key: string, mimeType: string): Promise<void>;
  /** What a client should load. See the contract above. */
  urlFor(key: string): string;
  /**
   * The stored file's size, and a stream of its bytes — the whole file, or
   * just `range` (inclusive, as HTTP ranges are). Null if there is no such
   * file. `size` is the full length either way, because a ranged reply has to
   * say how long the whole thing is.
   */
  open(
    key: string,
    range?: { readonly start: number; readonly end: number },
  ): Promise<{ stream: Readable; size: number } | null>;
  /** The full length of a stored file, without opening it. */
  sizeOf(key: string): Promise<number | null>;
  remove(key: string): Promise<void>;
}

const API_ROOT = fileURLToPath(new URL('../..', import.meta.url));

/** Uploads land here first, and only move into the store once checked. */
export const TEMP_DIR = join(API_ROOT, '.media', '.incoming');

/**
 * A key is generated by the server — `<vendorId>/<uuid>.<ext>` — and never
 * taken from a request. This pattern is still checked on every read, because
 * the read path IS taken from a request, and `../../.env` is a valid-looking
 * path to anybody trying one.
 */
export const KEY_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp|mp4|webm|mov)$/;

class LocalDiskStore implements MediaStore {
  private readonly root = join(API_ROOT, '.media', 'files');

  private pathFor(key: string): string {
    if (!KEY_PATTERN.test(key)) throw new Error(`Refusing a malformed media key: ${key}`);
    const full = resolve(this.root, key);
    // Belt and braces: the pattern already excludes `..`, but the resolved
    // path is checked too, so a future loosening of the pattern cannot quietly
    // reopen a traversal.
    if (!full.startsWith(resolve(this.root))) throw new Error('Media key escapes the store');
    return full;
  }

  async commit(tempPath: string, key: string): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(dirname(target), { recursive: true });
    await rename(tempPath, target);
  }

  urlFor(key: string): string {
    return `/media/${key}`;
  }

  async sizeOf(key: string): Promise<number | null> {
    try {
      return (await stat(this.pathFor(key))).size;
    } catch {
      return null;
    }
  }

  async open(
    key: string,
    range?: { readonly start: number; readonly end: number },
  ): Promise<{ stream: Readable; size: number } | null> {
    const size = await this.sizeOf(key);
    if (size === null) return null;
    const target = this.pathFor(key);
    return {
      stream: createReadStream(target, range === undefined ? {} : range),
      size,
    };
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }
}

let store: MediaStore | null = null;

/**
 * The configured store. Only the local one exists yet; `MEDIA_STORE=supabase`
 * is refused loudly rather than quietly falling back, because a production
 * deploy that silently writes uploads to a container's ephemeral disk loses
 * every logo on the next restart.
 */
export function mediaStore(): MediaStore {
  if (store !== null) return store;
  const kind = process.env['MEDIA_STORE'] ?? 'local';
  if (kind !== 'local') {
    throw new Error(
      `MEDIA_STORE=${kind} is not implemented yet. Only "local" exists; Supabase Storage is the next step before any deploy.`,
    );
  }
  store = new LocalDiskStore();
  return store;
}

export async function ensureTempDir(): Promise<string> {
  await mkdir(TEMP_DIR, { recursive: true });
  return TEMP_DIR;
}

export function tempWriter(path: string) {
  return createWriteStream(path);
}
